# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token b87dca35c984827565c3987af76bf98674f476d6

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/5/
Content-Type: application/json
Authorization: Token b87dca35c984827565c3987af76bf98674f476d6

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=2
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_after=2022-02-03
Content-Type: application/json

###

# пробуем удалять пост без токена

DELETE {{baseUrl}}/advertisements/10/
Content-Type: application/json
Authorization: Token b87dca35c984827565c3987af76bf98674f476d6