version: "3.8"

services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    env_file:
      - .env
  
  django:
    depends_on:
      - db
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
  
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8181:80"
