version: "3.8"

services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"

  django:
    image: python:3.8
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "
             python manage.py migrate 
             && python manage.py collectstatic 
             && gunicorn --bind 0.0.0.0:8000 stocks_products.wsgi"
    volumes:
      - static_volume:/code/staticfiles
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db
  
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/staticfiles
    ports:
      - "1337:80"
    depends_on:
      - django

volumes:
  static_volume:
