FROM python:3.8
WORKDIR /code
COPY . .
RUN pip install -r requirements.txt
RUN python manage.py migrate
ENV DEBUG=True
ENV SECRET_KEY=django-insecure-nw^y+m^wmxza1asgk+)!ua2qx9)g+#v=6%76-9i8i(6eqiw94j
EXPOSE 8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
