version: "3.8"

services:
  db:
    image: postgres
    restart: unless-stopped
    env_file:
      - .env
  
  django:
    depends_on:
      - db
    image: python:3.8
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
  
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8181:80"
